In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/engineering-colleges-in-india/engineering colleges in India.csv


In [3]:
import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_csv("/kaggle/input/engineering-colleges-in-india/engineering colleges in India.csv")

In [5]:
dataset.head()

College Name Genders Accepted  \
0         National Institute of Technology Rourkela             Co-Ed   
1  Visvesvaraya National Institute of Technology ...            Co-Ed   
2             Netaji Subhas University of Technology            Co-Ed   
3                      Birla Institute of Technology            Co-Ed   
4  International Institute of Information Technology            Co-Ed   

  Campus Size Total Student Enrollments Total Faculty Established Year Rating  \
0   647 Acres                      4811           329             2007   3.12   
1   215 Acres                      1071           192             2007    NaN   
2   145 Acres                      3759           101             2018    NaN   
3   980 Acres                      4506           284             1955    NaN   
4    66 Acres                      1721            85             2001   3.05   

  University                                            Courses  \
0        NaN  B.Tech Mechanical Engineering, B.Tech Computer...   
1        NaN  B.Tech Computer Science Engineering, B.Tech El...   
2        NaN  B.Tech Computer Engineering, B.Tech Electronic...   
3        NaN  B.Tech Computer Science Engineering, B.Tech El...   
4        NaN  B.Tech Computer Science and Engineering, M.Tec...   

                                          Facilities       City        State  \
0  Boys Hostel, Girls Hostel, Gym, Library, Sport...   Rourkela       Odisha   
1  Boys Hostel, Girls Hostel, Gym, Library, Sport...     Nagpur  Maharashtra   
2  Boys Hostel, Girls Hostel, Gym, Library, Sport...  New Delhi        Delhi   
3  Boys Hostel, Girls Hostel, Gym, Library, Sport...     Ranchi    Jharkhand   
4  Boys Hostel, Girls Hostel, Gym, Library, Sport...  Hyderabad    Telangana   

  Country       College Type       Average Fees  
0   India  Public/Government           350600.0  
1   India  Public/Government  273596.6666666667  
2   India  Public/Government           352320.0  
3   India            Private  596686.0465116279  
4   India            Private  756666.6666666666

In [7]:
dataset["overview"] = np.nan
dataset.head()

College Name Genders Accepted  \
0         National Institute of Technology Rourkela             Co-Ed   
1  Visvesvaraya National Institute of Technology ...            Co-Ed   
2             Netaji Subhas University of Technology            Co-Ed   
3                      Birla Institute of Technology            Co-Ed   
4  International Institute of Information Technology            Co-Ed   

  Campus Size Total Student Enrollments Total Faculty Established Year Rating  \
0   647 Acres                      4811           329             2007   3.12   
1   215 Acres                      1071           192             2007    NaN   
2   145 Acres                      3759           101             2018    NaN   
3   980 Acres                      4506           284             1955    NaN   
4    66 Acres                      1721            85             2001   3.05   

  University                                            Courses  \
0        NaN  B.Tech Mechanical Engineering, B.Tech Computer...   
1        NaN  B.Tech Computer Science Engineering, B.Tech El...   
2        NaN  B.Tech Computer Engineering, B.Tech Electronic...   
3        NaN  B.Tech Computer Science Engineering, B.Tech El...   
4        NaN  B.Tech Computer Science and Engineering, M.Tec...   

                                          Facilities       City        State  \
0  Boys Hostel, Girls Hostel, Gym, Library, Sport...   Rourkela       Odisha   
1  Boys Hostel, Girls Hostel, Gym, Library, Sport...     Nagpur  Maharashtra   
2  Boys Hostel, Girls Hostel, Gym, Library, Sport...  New Delhi        Delhi   
3  Boys Hostel, Girls Hostel, Gym, Library, Sport...     Ranchi    Jharkhand   
4  Boys Hostel, Girls Hostel, Gym, Library, Sport...  Hyderabad    Telangana   

  Country       College Type       Average Fees  overview  
0   India  Public/Government           350600.0       NaN  
1   India  Public/Government  273596.6666666667       NaN  
2   India  Public/Government           352320.0       NaN  
3   India            Private  596686.0465116279       NaN  
4   India            Private  756666.6666666666       NaN

In [22]:

for i in dataset.index:
#     dataset['overview'][i] = dataset.iloc['Campus Size[i]', 'Courses[i]', 'Facilities[i]', 'City[i]', 'State[i]', 'College Type[i]', 'Average Fees[i]'].to_string(header=False, index=False)
    
    temp = str(dataset['Campus Size'][i]) + str(dataset['Courses'][i]) + str(dataset['Facilities'][i]) + str(dataset['City'][i]) + str(dataset['State'][i]) + str(dataset['College Type'][i]) + str(dataset['Average Fees'][i])
    dataset['overview'][i] = temp

In [23]:
dataset.head(3)

College Name Genders Accepted  \
0         National Institute of Technology Rourkela             Co-Ed   
1  Visvesvaraya National Institute of Technology ...            Co-Ed   
2             Netaji Subhas University of Technology            Co-Ed   

  Campus Size Total Student Enrollments Total Faculty Established Year Rating  \
0   647 Acres                      4811           329             2007   3.12   
1   215 Acres                      1071           192             2007    NaN   
2   145 Acres                      3759           101             2018    NaN   

  University                                            Courses  \
0        NaN  B.Tech Mechanical Engineering, B.Tech Computer...   
1        NaN  B.Tech Computer Science Engineering, B.Tech El...   
2        NaN  B.Tech Computer Engineering, B.Tech Electronic...   

                                          Facilities       City        State  \
0  Boys Hostel, Girls Hostel, Gym, Library, Sport...   Rourkela       Odisha   
1  Boys Hostel, Girls Hostel, Gym, Library, Sport...     Nagpur  Maharashtra   
2  Boys Hostel, Girls Hostel, Gym, Library, Sport...  New Delhi        Delhi   

  Country       College Type       Average Fees  \
0   India  Public/Government           350600.0   
1   India  Public/Government  273596.6666666667   
2   India  Public/Government           352320.0   

                                            overview  
0  647 AcresB.Tech Mechanical Engineering, B.Tech...  
1  215 AcresB.Tech Computer Science Engineering, ...  
2  145 AcresB.Tech Computer Engineering, B.Tech E...

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [25]:
tfidf = TfidfVectorizer(stop_words="english")
dataset['overview'] = dataset['overview'].fillna("")
tfidf_matrix = tfidf.fit_transform(dataset['overview'])



In [26]:
from sklearn.metrics.pairwise import linear_kernel

In [27]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
print(cosine_sim)

[[1.         0.70632967 0.59298275 ... 0.09799318 0.05867414 0.06395764]
 [0.70632967 1.         0.64860959 ... 0.1307884  0.08093468 0.03489009]
 [0.59298275 0.64860959 1.         ... 0.08562098 0.04916262 0.00969817]
 ...
 [0.09799318 0.1307884  0.08562098 ... 1.         0.17818862 0.00273022]
 [0.05867414 0.08093468 0.04916262 ... 0.17818862 1.         0.00593207]
 [0.06395764 0.03489009 0.00969817 ... 0.00273022 0.00593207 1.        ]]


In [36]:
indices_clg = pd.Series(dataset.index, dataset['College Name']).drop_duplicates()
indices_overview = pd.Series(dataset.index, dataset['overview']).drop_duplicates()
print(indices_overview[indices_clg['Netaji Subhas University of Technology']])

print(dataset['overview'][2])

2
145 AcresB.Tech Computer Engineering, B.Tech Electronics and Communication Engineering, B.Tech Instrumentation and Control Engineering, B.Tech Biotechnology, B.Tech Information Technology, B.Tech Manufacturing Process and Automation Engineering, B.Tech Mechanical Engineering, BBA, MBA, M.Tech Biochemical Engineering, M.Tech Bioinformatics, M.Tech CAD CAM, M.Tech Computer Engineering, M.Tech Embedded System and VLSI, M.Tech Industrial Electronics, M.Tech Manufacturing Process and Automation Engineering, M.Tech Mechatronics, M.Tech Nanotechnology, M.Tech Process Control, M.Tech Production Engineering, M.Tech Signal Processing, Master of Engineering and Management, Ph.D Management Studies, M.Tech Computer Engineering Part Time, M.Tech Process Control Part Time, M.Tech Signal Processing Part Time, B.Tech Computer Science and Engineering with Specialisation in Artificial Intelligence, B.Tech Electrical Engineering, B.Tech Mathematics and Computing, Ph.D Biotechnology, Ph.D Chemistry, Ph.D

In [47]:
def get_recommendation(preferences, cosine_sim = cosine_sim):
    ind = indices_overview[preferences]
    sim_scores = enumerate(cosine_sim[ind])
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:6]
    
    sim_index = [i[0] for i in sim_scores]
    print(dataset["College Name"].iloc[sim_index])
    
  
get_recommendation("145 AcresB.Tech Computer Engineering, B.Tech Electronics and Communication Engineering, B.Tech Instrumentation and Control Engineering, B.Tech Biotechnology, B.Tech Information Technology, B.Tech Manufacturing Process and Automation Engineering, B.Tech Mechanical Engineering, BBA, MBA, M.Tech Biochemical Engineering, M.Tech Bioinformatics, M.Tech CAD CAM, M.Tech Computer Engineering, M.Tech Embedded System and VLSI, M.Tech Industrial Electronics, M.Tech Manufacturing Process and Automation Engineering, M.Tech Mechatronics, M.Tech Nanotechnology, M.Tech Process Control, M.Tech Production Engineering, M.Tech Signal Processing, Master of Engineering and Management, Ph.D Management Studies, M.Tech Computer Engineering Part Time, M.Tech Process Control Part Time, M.Tech Signal Processing Part Time, B.Tech Computer Science and Engineering with Specialisation in Artificial Intelligence, B.Tech Electrical Engineering, B.Tech Mathematics and Computing, Ph.D Biotechnology, Ph.D Chemistry, Ph.D Computer Engineering, Ph.D Electronics and Communication Engineering, Ph.D Humanities and Social Sciences, Ph.D Information Technology, Ph.D Instrumentation and Control Engineering, Ph.D Manufacturing Process and Automation Engineering, Ph.D Mathematics, Ph.D PhysicsBoys Hostel, Girls Hostel, Gym, Library, Sports, Cafeteria, Medical/Hospital, Wifi, IT Infrastructure, Laboratories, Convenience Store, Alumni AssociationsNew DelhiDelhiPublic/Government352320.0")

53          National Institute of Technology Silchar 
706                     GITAM Institute of Technology
31           Indian Institute of Technology Guwahati 
1155                       GITAM School of Technology
25      National Institute of Technology Kurukshetra 
Name: College Name, dtype: object
